FROM tensorflow/tensorflow:1.12.0-devel-gpu-py3

MAINTAINER Thomas Boquet <thomas@elementai.com>


ARG PIP_EXTRA_INDEX_URL

RUN apt-get update && apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install eai-shuriken

WORKDIR /TADAM/TADAM

ENV DATA_PATH=/data

COPY . .

RUN ls -alh

CMD ["python3", "-m", "model.tadam"]
